src/CoachsBox.WebApp/Areas/Admin/Pages/Branches/Create.cshtml.cs
using System.Threading.Tasks;
using CoachsBox.WebApp.Areas.Admin.Facade;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CoachsBox.WebApp.Areas.Admin.Pages.Branches
{
  public class CreateModel : PageModel
  {
    private readonly IAdministrationServiceFacade administrationService;

    public CreateModel(
      IAdministrationServiceFacade administrationService)
    {
      this.administrationService = administrationService;
    }

    public async Task<IActionResult> OnGet()
    {
      this.CreateCommand = new CreateBranchCommand();
      return Page();
    }

    [BindProperty]
    public CreateBranchCommand CreateCommand { get; set; }

    public IActionResult OnPost()
    {
      if (!this.ModelState.IsValid)
      {
        return this.Page();
      }

      var branchId = this.administrationService.CreateBranch(this.CreateCommand);
      return RedirectToPage("./Details", new { branchId });
    }
  }
}

src/CoachsBox.WebApp/Areas/Admin/Pages/Branches/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using CoachsBox.Coaching.BranchModel;
using CoachsBox.Coaching.Infrastructure;

namespace CoachsBox.WebApp.Areas.Admin.Pages.Branches
{
    public class DeleteModel : PageModel
    {
        private readonly CoachsBox.Coaching.Infrastructure.CoachsBoxContext _context;

        public DeleteModel(CoachsBox.Coaching.Infrastructure.CoachsBoxContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Branch Branch { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Branch = await _context.Branches
                .Include(b => b.ContactPerson).FirstOrDefaultAsync(m => m.Id == id);

            if (Branch == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Branch = await _context.Branches.FindAsync(id);

            if (Branch != null)
            {
                _context.Branches.Remove(Branch);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

src/CoachsBox.WebApp/Areas/Admin/Pages/Branches/Details.cshtml.cs
using System.Threading.Tasks;
using CoachsBox.Coaching.BranchModel;
using CoachsBox.WebApp.Areas.Admin.Facade.DTO;
using CoachsBox.WebApp.Areas.Admin.Facade.Internal;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CoachsBox.WebApp.Areas.Admin.Pages.Branches
{
  public class DetailsModel : PageModel
  {
    private readonly IBranchRepository branchRepository;

    public DetailsModel(IBranchRepository branchRepository)
    {
      this.branchRepository = branchRepository;
    }

    public BranchDTO Branch { get; set; }

    public async Task<IActionResult> OnGetAsync(int? branchId)
    {
      if (branchId == null)
        return NotFound();

      var assembler = new BranchDTOAssembler();
      var branch = await this.branchRepository.GetByIdAsync(branchId.Value);
      this.Branch = assembler.ToDTO(branch);

      if (Branch == null)
        return NotFound();

      return Page();
    }
  }
}

src/CoachsBox.WebApp/Areas/Admin/Pages/Branches/Edit.cshtml.cs
using CoachsBox.WebApp.Areas.Admin.Facade;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CoachsBox.WebApp.Areas.Admin.Pages.Branches
{
  public class EditModel : PageModel
  {
    private readonly IAdministrationServiceFacade administrationService;

    public EditModel(IAdministrationServiceFacade administrationService)
    {
      this.administrationService = administrationService;
    }

    [BindProperty]
    public CreateBranchCommand EditCommand { get; set; }

    public IActionResult OnGetAsync(int branchId)
    {
      if (branchId <= 0)
      {
        return NotFound();
      }

      this.EditCommand = this.administrationService.EditBranch(branchId);

      return Page();
    }

    public IActionResult OnPost(int branchId)
    {
      if (branchId <= 0)
      {
        return NotFound();
      }

      if (!ModelState.IsValid)
      {
        return Page();
      }

      this.administrationService.UpdateBranch(branchId, this.EditCommand);

      return RedirectToPage("./Index");
    }
  }
}

src/CoachsBox.WebApp/Areas/Admin/Pages/Coaches/Create.cshtml.cs
using System.Linq;
using CoachsBox.Coaching.PersonModel;
using CoachsBox.WebApp.AppFacade.Coaches.Commands;
using CoachsBox.WebApp.Areas.Admin.Facade;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CoachsBox.WebApp.Areas.Admin.Pages.Coaches
{
  public class CreateModel : PageModel
  {
    private readonly IAdministrationServiceFacade administrativeServiceFacade;

    public CreateModel(
      IAdministrationServiceFacade administrativeServiceFacade)
    {
      this.administrativeServiceFacade = administrativeServiceFacade;
    }

    [BindProperty]
    public CreateCoachCommand CreateCommand { get; set; }

    public IActionResult OnGet(int? branchId)
    {
      this.CreateCommand = new CreateCoachCommand()
      {
        Gender = Gender.Male.Value
      };

      if (branchId != null)
        this.CreateCommand.BranchId = branchId.Value;

      return Page();
    }

    public IActionResult OnPost()
    {
      if (!ModelState.IsValid)
        return Page();

      var existingPersons = this.administrativeServiceFacade.FindExistCoach(this.CreateCommand);
      if (existingPersons.Any())
      {
        // TODO: Список похожих персон.
        this.ModelState.AddModelError("CreateCommand.Name", "Тренер(ы) с похожим именем уже существует(ют)");
        return this.Page();
      }

      var coachId = this.administrativeServiceFacade.CreateCoach(this.CreateCommand);
      return RedirectToPage("./Details", new { coachId });
    }
  }
}

src/CoachsBox.WebApp/Areas/Admin/Pages/Coaches/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using CoachsBox.Coaching.CoachModel;
using CoachsBox.Coaching.Infrastructure;

namespace CoachsBox.WebApp.Areas.Admin.Pages.Coaches
{
    public class DeleteModel : PageModel
    {
        private readonly CoachsBox.Coaching.Infrastructure.CoachsBoxContext _context;

        public DeleteModel(CoachsBox.Coaching.Infrastructure.CoachsBoxContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Coach Coach { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Coach = await _context.Coaches
                .Include(c => c.Person).FirstOrDefaultAsync(m => m.Id == id);

            if (Coach == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Coach = await _context.Coaches.FindAsync(id);

            if (Coach != null)
            {
                _context.Coaches.Remove(Coach);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

src/CoachsBox.WebApp/Areas/Admin/Pages/Coaches/Details.cshtml.cs
using System;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using CoachsBox.Coaching.CoachModel;
using CoachsBox.WebApp.Areas.Admin.Facade.DTO;
using CoachsBox.WebApp.Areas.Admin.Facade.Internal;
using CoachsBox.WebApp.Areas.Identity.Commands;
using CoachsBox.WebApp.Areas.Identity.Data;
using CoachsBox.WebApp.Resources;
using MediatR;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Localization;

namespace CoachsBox.WebApp.Areas.Admin.Pages.Coaches
{
  public class DetailsModel : PageModel
  {
    private readonly ICoachRepository coachRepository;
    private readonly UserManager<CoachsBoxWebAppUser> userManager;
    private readonly IMediator mediator;
    private readonly IStringLocalizer<IdentityResource> stringLocalizer;

    public DetailsModel(
      ICoachRepository coachRepository,
      UserManager<CoachsBoxWebAppUser> userManager,
      IMediator mediator,
      IStringLocalizer<IdentityResource> stringLocalizer)
    {
      this.coachRepository = coachRepository;
      this.userManager = userManager;
      this.mediator = mediator;
      this.stringLocalizer = stringLocalizer;
    }

    public CoachDTO Coach { get; set; }

    public int PersonId { get; set; }

    public string AccountStatusStyle { get; set; }

    public string AccountStatus { get; set; }

    public string AccountStatusDetails { get; set; }

    public string AccountActionTitle { get; set; }

    public string AccountActionHandler { get; set; }

    public string AccountEmail { get; set; }

    public bool AccountEmailChangedFromCoach { get; set; }

    public async Task<IActionResult> OnGetAsync(int? coachId)
    {
      if (coachId == null)
        return NotFound();

      var coach = await this.coachRepository.GetByIdAsync(coachId.Value);

      if (coach == null)
        return NotFound();

      this.FillProperties(coach);

      return Page();
    }

    public async Task<IActionResult> OnPostInvite(int coachId, int personId)
    {
      var user = this.userManager.Users.SingleOrDefault(user => user.PersonId == personId);
      if (user == null)
      {
        var coach = await this.coachRepository.GetByIdAsync(coachId);
        if (coach == null)
          return this.NotFound();

        var addUserResult = await this.mediator.Send(new CreateCoachUserCommand(coach.Person.Email(), coach.Person.PhoneNumber(), coach.PersonId));
        if (addUserResult.IsSucceeded())
          await this.mediator.Send(new SendInvitationCommand(addUserResult.UserId));
        else
        {
          foreach (var addUserError in addUserResult.IdentityResult.Errors)
            this.ModelState.TryAddModelError(addUserError.Code, this.stringLocalizer.GetString(addUserError.Code));

          this.FillProperties(coach);
          return this.Page();
        }
      }
      else if (!user.EmailConfirmed)
        await this.mediator.Send(new SendInvitationCommand(user.Id));

      return this.RedirectToPage("Details", new { coachId });
    }

    public async Task<IActionResult> OnPostUpdateUserName(int coachId, string userName)
    {
      var coach = await this.coachRepository.GetByIdAsync(coachId);
      if (coach == null)
        return this.NotFound();

      var newEmail = coach.Person.Email();
      var updateResult = await this.mediator.Send(new UpdateUserNameAndEmailCommand(userName, newEmail, newEmail));
      if (updateResult.Succeeded)
        return this.RedirectToPage("Details", new { coachId });

      foreach (var updateError in updateResult.Errors)
        this.ModelState.TryAddModelError(updateError.Code, this.stringLocalizer.GetString(updateError.Code) ?? updateError.Description);

      this.FillProperties(coach);
      return this.Page();
    }

    public void FillProperties(Coach coach)
    {
      var assembler = new CoachDTOAssembler();
      this.Coach = assembler.ToDTO(coach);
      this.PersonId = coach.PersonId;

      var user = this.userManager.Users.SingleOrDefault(user => user.PersonId == coach.PersonId);
      if (user == null)
      {
        this.AccountStatus = "Приглашение не отправлено";
        this.AccountStatusStyle = "primary";
        this.AccountStatusDetails = "Тренер не получал приглашение на эл. почту.";
        this.AccountActionTitle = "Пригласить";
        this.AccountActionHandler = "Invite";
      }
      else
      {
        this.AccountEmail = user.Email.ToLower(CultureInfo.CurrentUICulture);
        this.AccountEmailChangedFromCoach = !string.Equals(user.UserName, coach.Person.Email(), StringComparison.OrdinalIgnoreCase);

        if (!user.EmailConfirmed)
        {
          this.AccountStatus = "Ожидание подтверждения";
          this.AccountStatusStyle = "warning";
          this.AccountStatusDetails = $"Тренер не подтвердил эл. почту '{this.AccountEmail}'.";
          this.AccountActionTitle = "Отправить приглашение";
          this.AccountActionHandler = "Invite";
        }
        else
        {
          this.AccountStatus = "Приглашён";
          this.AccountStatusStyle = "success";
          this.AccountStatusDetails = $"Тренер подтвердил эл. почту '{this.AccountEmail}' и может пользоваться системой.";
        }
      }
    }
  }
}

src/CoachsBox.WebApp/Areas/Admin/Pages/Coaches/Edit.cshtml.cs
using System.Threading.Tasks;
using CoachsBox.Coaching.CoachModel;
using CoachsBox.WebApp.AppFacade.Coaches.Commands;
using CoachsBox.WebApp.Areas.Admin.Facade;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CoachsBox.WebApp.Areas.Admin.Pages.Coaches
{
  public class EditModel : PageModel
  {
    private readonly IAdministrationServiceFacade administrationService;
    private readonly ICoachRepository coachRepository;

    public EditModel(
      IAdministrationServiceFacade administrationService,
      ICoachRepository coachRepository)
    {
      this.administrationService = administrationService;
      this.coachRepository = coachRepository;
    }

    [BindProperty]
    public InputCoachCommand InputCommand { get; set; }

    public async Task<IActionResult> OnGetAsync(int? coachId)
    {
      if (coachId == null)
        return this.NotFound();

      var coach = await this.coachRepository.GetByIdAsync(coachId.Value);
      if (coach == null)
        return this.NotFound();

      this.InputCommand = new InputCoachCommand(coach);

      return this.Page();
    }

    public IActionResult OnPost()
    {
      if (!ModelState.IsValid)
        return this.Page();

      this.administrationService.UpdateCoach(this.InputCommand);

      return this.RedirectToPage("./Index");
    }
  }
}

src/CoachsBox.WebApp/Areas/Admin/Pages/Coaches/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using CoachsBox.Coaching.CoachModel;
using CoachsBox.Coaching.Infrastructure;
using CoachsBox.WebApp.Areas.Admin.Facade.DTO;
using CoachsBox.WebApp.Areas.Admin.Facade.Internal;

namespace CoachsBox.WebApp.Areas.Admin.Pages.Coaches
{
  public class IndexModel : PageModel
  {
    private readonly ICoachRepository coachRepository;

    public IndexModel(ICoachRepository context)
    {
      coachRepository = context;
    }

    public IList<CoachDTO> Coaches { get; set; }

    public async Task OnGetAsync()
    {
      var coaches = await coachRepository.ListAllAsync();
      var assembler = new CoachDTOAssembler();
      var orderedCoasches = coaches.OrderBy(c => c.Person.Name.FullName());
      this.Coaches = assembler.ToDTOList(orderedCoasches);
    }
  }
}

src/CoachsBox.WebApp/Areas/Admin/Pages/Salaries/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CoachsBox.WebApp.Areas.Admin.Pages.Salaries
{
  public class EditModel : PageModel
  {
    public int SalaryId { get; set; }

    public void OnGet(int salaryId)
    {
      this.SalaryId = salaryId;
    }
  }
}

src/CoachsBox.WebApp/Areas/Admin/Pages/Tariffs/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoachsBox.WebApp.Areas.Admin.Facade;
using CoachsBox.WebApp.Areas.Admin.Facade.DTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CoachsBox.WebApp.Areas.Admin.Pages.Tariffs
{
  public class DetailsModel : PageModel
  {
    private readonly IAccountingServiceFacade accountingServiceFacade;

    public DetailsModel(IAccountingServiceFacade accountingServiceFacade)
    {
      this.accountingServiceFacade = accountingServiceFacade;
    }

    public TariffDTO Tariff { get; set; }

    public IActionResult OnGet(int tariffId)
    {
      if (tariffId == 0)
        return this.NotFound();

      this.Tariff = this.accountingServiceFacade.ViewTariff(tariffId);
      if (this.Tariff == null)
        return this.NotFound();

      return this.Page();
    }
  }
}

src/CoachsBox.WebApp/Pages/Attendance/Edit.cshtml.cs
using System;
using CoachsBox.WebApp.Areas.Identity.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CoachsBox.WebApp.Pages.Attendance
{
  public class EditModel : PageModel
  {
    public int CoachId { get; private set; }

    public int GroupId { get; private set; }

    public DateTime Date { get; private set; }

    public TimeSpan Start { get; private set; }

    public TimeSpan End { get; private set; }

    public IActionResult OnGet(int groupId, DateTime date, TimeSpan start, TimeSpan end)
    {
      this.CoachId = this.User.GetCoachId();
      this.GroupId = groupId;
      this.Date = date;
      this.Start = start;
      this.End = end;
      return this.Page();
    }
  }
}

src/CoachsBox.WebApp/Areas/Admin/Pages/Coaches/Create.cshtml
@page
@model CoachsBox.WebApp.Areas.Admin.Pages.Coaches.CreateModel

@{ Layout = "~/Pages/Shared/_Layout.cshtml";
  ViewData["Title"] = "Новый тренер"; }

<h1>@ViewData["Title"]</h1>
<hr />
<div class="row">
  <form method="post" class="col col-sm col-md col-xl-6 col-lg-6">
    <div asp-validation-summary="All" class="text-danger"></div>
    <partial name="_CoachEditorPartial" for="CreateCommand" />
    <div class="form-group">
      <input type="submit" value="Добавить тренера" class="btn btn-primary" />
      <a asp-page="Index" class="btn btn-secondary">Отмена</a>
    </div>
  </form>
</div>

@section Scripts {
  <partial name="_ValidationScriptsPartial" />
  <partial name="PersonEditorsPartial/AddressScripts" for="CreateCommand" />
}

src/CoachsBox.WebApp/Areas/Admin/Pages/Coaches/Delete.cshtml
@page
@model CoachsBox.WebApp.Areas.Admin.Pages.Coaches.DeleteModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Coach</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Coach.Person)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Coach.Person.Id)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Coach.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

src/CoachsBox.WebApp/Areas/Admin/Pages/Coaches/Details.cshtml
@page
@model CoachsBox.WebApp.Areas.Admin.Pages.Coaches.DetailsModel

@{
  ViewData["Title"] = this.Model.Coach.FullName;
  Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h3>@Model.Coach.FullName</h3>

<div>
  <hr />

  <div class="row">
    <div class="col-sm-5 mb-1">
      <div class="card">
        <div class="card-header">
          Общие сведения
        </div>
        <ul class="list-group list-group-flush">
          @if (!string.IsNullOrWhiteSpace(this.Model.Coach.Birthday))
          {
            <li class="list-group-item" title="@Html.DisplayNameFor(model => model.Coach.Birthday)">
              <i class="fas fa-birthday-cake text-success mr-3"></i>@Html.DisplayFor(model => model.Coach.Birthday)
            </li>
          }
          @if (!string.IsNullOrWhiteSpace(this.Model.Coach.Address))
          {
            <li class="list-group-item" title="@Html.DisplayNameFor(model => model.Coach.Address)">
              <i class="fas fa-map-marker-alt text-secondary mr-3"></i>@Html.DisplayFor(model => model.Coach.Address)
            </li>
          }
          @if (!string.IsNullOrWhiteSpace(this.Model.Coach.PhoneNumber))
          {
            <li class="list-group-item" title="@Html.DisplayNameFor(model => model.Coach.PhoneNumber)">
              <i class="fas fa-phone text-danger mr-3"></i>@Html.DisplayFor(model => model.Coach.PhoneNumber)
            </li>
          }
          @if (!string.IsNullOrWhiteSpace(this.Model.Coach.Email))
          {
            <li class="list-group-item" title="@Html.DisplayNameFor(model => model.Coach.Email)">
              <i class="fas fa-at text-info mr-3"></i>@Html.DisplayFor(model => model.Coach.Email)
            </li>
          }
        </ul>
        <div class="card-body">
          <a class="card-link" asp-page="./Edit" asp-route-coachId="@Model.Coach.Id">Изменить</a>
        </div>
      </div>
    </div>

    <div class="col-sm-7 mb-1">
      <div class="card">
        <div class="card-header">Доступ в систему</div>
        <div class="card-body">
          @if (this.Model.ModelState.ErrorCount > 0)
          {
            <div class="alert alert-danger" role="alert">
              <div asp-validation-summary="All"></div>
            </div>
          }

          @if (this.Model.AccountEmailChangedFromCoach)
          {
            <div class="alert alert-warning" role="alert">
              Эл. почта тренера '<b>@this.Model.Coach.Email</b>' отличается от эл. почты, используемой для входа в систему '<b>@this.Model.AccountEmail</b>' <br />
              <form autocomplete="off" method="post">
                <button type="submit" class="btn btn-link px-0"
                        asp-page="Details"
                        asp-route-coachId="@Model.Coach.Id"
                        asp-route-userName="@Model.AccountEmail"
                        asp-page-handler="UpdateUserName">
                  Обновить данные для входа
                </button>
              </form>
            </div>
          }

          @{ var titleClassName = $"text-{Model.AccountStatusStyle}"; }
          <h5 class="card-title @titleClassName">@Model.AccountStatus</h5>
          <p class="card-text">@Model.AccountStatusDetails</p>
          @if (!string.IsNullOrWhiteSpace(Model.AccountActionTitle) && !string.IsNullOrWhiteSpace(Model.AccountActionHandler))
          {
            <form autocomplete="off" method="post">
              <button type="submit" class="btn btn-primary"
                      asp-page="Details"
                      asp-route-coachId="@Model.Coach.Id"
                      asp-route-personId="@Model.PersonId"
                      asp-page-handler="@Model.AccountActionHandler">
                @Model.AccountActionTitle
              </button>
            </form>
          }
        </div>
      </div>
    </div>
  </div>

src/CoachsBox.WebApp/Areas/Admin/Pages/Coaches/Edit.cshtml
@page
@model CoachsBox.WebApp.Areas.Admin.Pages.Coaches.EditModel

@{
  ViewData["Title"] = "Изменение тренера";
  Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>@ViewData["Title"]</h1>
<hr />
<div class="row">
  <form method="post" class="col col-sm col-md col-xl-6 col-lg-6">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    @Html.HiddenFor((model) => model.InputCommand.Id)
    <partial name="_CoachEditorPartial" for="InputCommand" />
    <div class="form-group">
      <input type="submit" value="Сохранить" class="btn btn-primary" />
      <a asp-page="Index" class="btn btn-secondary">Отмена</a>
    </div>
  </form>
</div>

@section Scripts {
  <partial name="_ValidationScriptsPartial" />
  <partial name="PersonEditorsPartial/AddressScripts" for="InputCommand" />
}

src/CoachsBox.WebApp/Areas/Admin/Pages/Coaches/Index.cshtml
@page
@model CoachsBox.WebApp.Areas.Admin.Pages.Coaches.IndexModel

@{
  ViewData["Title"] = "Тренера";
  Layout = "~/Pages/Shared/_Layout.cshtml";
}

<div class="card">
  <div class="card-header">
    <span class="h3">@ViewData["Title"]</span>
    <a class="float-right align-middle btn btn-success" asp-page="Create">Добавить</a>
  </div>
  <ul class="list-group list-group-flush">
    @foreach (var coachDTO in Model.Coaches)
    {
      <li class="list-group-item">
        <!-- Фотка человека -->
        <div class="float-left"></div>
        <div>
          <a class="font-weight-bold" asp-page="./Details" asp-route-coachId="@coachDTO.Id">@Html.DisplayFor(modelItem => coachDTO.FullName)</a>
          <div>
            <div class="float-left mr-3">
              <span class="small font-weight-bold">📞</span>
              <span class="small">@Html.DisplayFor(modelItem => coachDTO.PhoneNumber)</span>
            </div>
            <div class="float-left mr-3">
              <span class="small font-weight-bold">📧</span>
              <span class="small">@Html.DisplayFor(modelItem => coachDTO.Email)</span>
            </div>
            <div class="float-left mr-3">
              <span class="small font-weight-bold">@Html.DisplayNameFor(modelItem => coachDTO.Address):</span>
              <span class="small">@Html.DisplayFor(modelItem => coachDTO.Address)</span>
            </div>
          </div>
        </div>
      </li>
    }
  </ul>
</div>

src/CoachsBox.WebApp/Areas/Admin/Pages/Coaches/_CoachEditorPartial.cshtml
@using CoachsBox.WebApp.AppFacade.Primitives.Commands
@model CreatePersonCommand


<div class="form-row">
  <div class="col-md">
    <partial name="PersonEditorsPartial/Surname" model="@this.Model" />
  </div>
  <div class="col-md">
    <partial name="PersonEditorsPartial/Name" model="@this.Model" />
  </div>
</div>

<partial name="PersonEditorsPartial/Patronymic" model="@this.Model" />

<div class="form-row">
  <div class="col-md">
    <partial name="PersonEditorsPartial/Sex" model="@this.Model" />
  </div>
  <div class="col-md">
    <partial name="PersonEditorsPartial/Birthdate" model="@this.Model" />
  </div>
</div>

<partial name="PersonEditorsPartial/Address" model="@this.Model" />

<partial name="PersonEditorsPartial/Phone" model="@this.Model" />

<partial name="PersonEditorsPartial/Email" model="@this.Model" />